export const students = [
  {
    _id: "1",
    name: "John Doe",
    fatherName: "Michael Doe",
    motherName: "Sarah Doe",
    age: 20,
    gender: "Male",
    course: "BSc Computer Science",
    department: "Computer Science",
    admissionDate: "2023-08-01",
    address: "123 Main St, City Name, State, 12345",
    email: "john.doe@example.com",
    phone: "123-456-7890",
    dateOfBirth: "2004-07-15",
  },
  {
    _id: "2",
    name: "Jane Smith",
    fatherName: "Robert Smith",
    motherName: "Emily Smith",
    age: 22,
    gender: "Female",
    course: "BBA",
    department: "Business Administration",
    admissionDate: "2022-09-01",
    address: "456 Another St, City Name, State, 67890",
    email: "jane.smith@example.com",
    phone: "987-654-3210",
    dateOfBirth: "2002-03-05",
  },
  {
    _id: "3",
    name: "Amit Kumar",
    fatherName: "Ramesh Kumar",
    motherName: "Sunita Kumar",
    age: 21,
    gender: "Male",
    course: "BTech Mechanical Engineering",
    department: "Mechanical Engineering",
    admissionDate: "2023-06-15",
    address: "789 Sample Rd, City Name, State, 11223",
    email: "amit.kumar@example.com",
    phone: "456-789-0123",
    dateOfBirth: "2003-01-22",
  },
  {
    _id: "4",
    name: "Sophia Patel",
    fatherName: "Vijay Patel",
    motherName: "Pooja Patel",
    age: 19,
    gender: "Female",
    course: "BSc Biology",
    department: "Biology",
    admissionDate: "2023-07-05",
    address: "101 College St, City Name, State, 33445",
    email: "sophia.patel@example.com",
    phone: "567-890-1234",
    dateOfBirth: "2005-05-10",
  },
  {
    _id: "5",
    name: "Carlos Fernandez",
    fatherName: "Antonio Fernandez",
    motherName: "Maria Fernandez",
    age: 23,
    gender: "Male",
    course: "MBA",
    department: "Business Management",
    admissionDate: "2021-08-15",
    address: "202 Oak Ave, City Name, State, 44556",
    email: "carlos.fernandez@example.com",
    phone: "678-901-2345",
    dateOfBirth: "2001-04-20",
  },
  {
    _id: "6",
    name: "Li Wei",
    fatherName: "Zhang Wei",
    motherName: "Liu Wei",
    age: 22,
    gender: "Male",
    course: "MSc Mathematics",
    department: "Mathematics",
    admissionDate: "2022-09-25",
    address: "303 Pine Rd, City Name, State, 55667",
    email: "li.wei@example.com",
    phone: "789-012-3456",
    dateOfBirth: "2002-08-10",
  },
  {
    _id: "7",
    name: "Olivia Brown",
    fatherName: "Samuel Brown",
    motherName: "Lisa Brown",
    age: 21,
    gender: "Female",
    course: "BA English",
    department: "English Literature",
    admissionDate: "2022-10-10",
    address: "404 Maple Blvd, City Name, State, 66778",
    email: "olivia.brown@example.com",
    phone: "890-123-4567",
    dateOfBirth: "2003-06-12",
  },
  {
    _id: "8",
    name: "Henry James",
    fatherName: "Peter James",
    motherName: "Helen James",
    age: 24,
    gender: "Male",
    course: "MA History",
    department: "History",
    admissionDate: "2021-11-10",
    address: "505 Elm St, City Name, State, 77889",
    email: "henry.james@example.com",
    phone: "901-234-5678",
    dateOfBirth: "1999-12-22",
  },
  {
    _id: "9",
    name: "Evelyn Garcia",
    fatherName: "Juan Garcia",
    motherName: "Carmen Garcia",
    age: 19,
    gender: "Female",
    course: "BFA Fine Arts",
    department: "Arts",
    admissionDate: "2023-05-20",
    address: "606 Birch Ln, City Name, State, 88990",
    email: "evelyn.garcia@example.com",
    phone: "012-345-6789",
    dateOfBirth: "2005-09-01",
  },
  {
    _id: "10",
    name: "Zachary Wilson",
    fatherName: "George Wilson",
    motherName: "Natalie Wilson",
    age: 22,
    gender: "Male",
    course: "BEng Electrical Engineering",
    department: "Electrical Engineering",
    admissionDate: "2021-07-30",
    address: "707 Cedar Rd, City Name, State, 99001",
    email: "zachary.wilson@example.com",
    phone: "234-567-8901",
    dateOfBirth: "2002-11-05",
  },
];
